export const MODEL_REGIONS = {
  brainLobs: {
    1: "Corpus Callosum",
    2: "Frontal lobe",
    3: "Parietal lobe",
    4: "Temporal lobe",
    5: "Occipital lobe",
    6: "Central Sulcus",
    7: "Lateral Sulcus",
    8: "Parieto-Occipital Sulcus",
    9: "Callosal Sulcus",
    10: "Cingulate Sulcus",
  },
  limbicSystem: {
    1: "Amygdala",
    2: "Hippocampus",
    3: "Anterior Cingulate Cortex",
    4: "Hypothalamus",
    5: "Pituitary Glad",
  },
  neuron: {
    1: "Axon Terminal",
    2: "Node of Ranvier",
    3: "Schwann Cell",
    4: "Myelin Sheath",
    5: "Axon",
    6: "Soma",
    7: "Dendrites",
    8: "Nucleus",
  },
  visualPathway: {
    1: "Visual Field",
    2: "Retina",
    3: "Optic Nerve",
    4: "Optic Chiasma",
    5: "Optic Tract",
    6: "Lateral Geniculate Nucleus",
    7: "Optic Radiation",
    8: "Occipital Lobe",
  },
  cerebralArteries: {
    1: "Anterior Cerebral Artery",
    2: "Middle Cerebral Artery",
    3: "Posterior Cerebral Artery",
    4: "Circle of Willis",
    5: "Basilar Artery",
  },
  ventricularSystem: {
    1: "Right Lateral Ventricle",
    2: "Left Lateral Ventricle",
    3: "3rd Ventricle",
    4: "Cerebral Aqueduct",
    5: "4th Ventricle",
    6: "Central Canal of Spinal Cord",
    7: "Left Interventricular Foramen",
    8: "Right Interventricular Foramen",
  },
  brodmannAreasAndPathologies:{
    1: "Frontal Lobe Lesion",
    2: "Frontal Eye Field Lesion",
    3: "PPRF Lesion",
    4: "Medial Longitudinal Fasciculus Lesions",
    5: "Dominant Parietal Cortex Lesions",
    6: "Nondominant Parietal Cortex Lesions",
    7: "Hippocampus Lesions",
    8: "Basal Ganlia Lesions",
    9: "Mammillary Body Lesions",
    10: "Amygdala Lesions",
    11:"Superior Colliculus Lesions",
    12:"Reticular Activating System (midbain)",
    13:"Cerebellar Hemisphere Lesions",
    14:"Cerebellar Vermis Lesions",
  }
};
