import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Brainteract",
  description: "Generated by firat altun",
};

import { BrainRegionProvider } from "@/context/brain-region-context";
import {
  SidebarInset,
  SidebarProvider
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <BrainRegionProvider>
          <SidebarProvider
            style={
              {
                "--sidebar-width": "350px",
              } as React.CSSProperties
            }
          >
            <AppSidebar />
            <SidebarInset>
              <main>
              {children}
              </main>
            </SidebarInset>
          </SidebarProvider>
        </BrainRegionProvider>
      </body>
    </html>
  );
}
